const js = require('@eslint/js')
const globals = require('globals')
const react = require('eslint-plugin-react')
const { defineConfig } = require('eslint/config')
const hooks = require('eslint-plugin-react-hooks')

module.exports = defineConfig([
  {
    files: ['src/**/*.js'],
    ...hooks.configs['recommended-latest'],
  },
  {
    files: ['src/**/*.js'],
    ...react.configs.flat.all,
    languageOptions: {
      ...react.configs.flat.all.languageOptions,
      globals: {
        ...globals.browser,
        preload: 'readonly',
      },
    },
    rules: {
      ...react.configs.flat.recommended.rules,
      'react/jsx-indent': ['warn', 2],
      'react/prop-types': 'off', // with the release of React 19 where PropTypes are removed ¯\_(ツ)_/¯
      'react/jsx-closing-tag-location': ['warn', 'line-aligned'],
      'react/jsx-filename-extension': ['warn', { extensions: ['.js'] }],
    },
  },
  {
    files: ['**/*.js'],
    ignores: ['.webpack/**', '.build/**'],
    plugins: { js },
    extends: ['js/recommended'],
    languageOptions: {
      globals: {
        ...globals.node,
        // NOTE variables generated by the electron-forge @see https://www.electronforge.io/config/plugins/webpack#main-process-code
        LAUNCHER_WEBPACK_ENTRY: 'readonly',
        LAUNCHER_PRELOAD_WEBPACK_ENTRY: 'readonly',
        INITIALIZER_WEBPACK_ENTRY: 'readonly',
        INITIALIZER_PRELOAD_WEBPACK_ENTRY: 'readonly',
      },
    },
    rules: {
      eqeqeq: ['warn', 'smart'],
      semi: ['warn', 'never'],
      quotes: ['warn', 'single'],
      curly: ['warn', 'multi-line'],
      'quote-props': ['warn', 'as-needed'],
      'no-console': ['warn', { allow: ['error'] }],
      'semi-spacing': ['warn', { before: false, after: true }],
      'no-unused-vars': ['warn', { vars: 'local', args: 'none', ignoreRestSiblings: true, varsIgnorePattern: '[iI]gnored', caughtErrors: 'none' }],
    }
  },
])
